### ISSUE TITLE
Crashes when started from Seafile

### ISSUE THREAD

**Issue by JanoschDeurer** [plafue/writeily-pro#153]
If I edit a .md file in the Seafile app I get the message: "Unfortunately, Writeily Pro has stopped."

How to reproduce it:
* Create a markdown file and upload it to your Seafile
* Open the markdown file in Seafile, the integrated Markdwon viewer should give you a preview
* Click "EDIT" in the upper right corner

I'm using the app out of the Android App Store so if this is already fixed I'm sorry.

**Comment by jkufner** [comment]
Same when opening a markdown file from Syncopoly. The exception is:

~~~~~
E/AndroidRuntime(29533): FATAL EXCEPTION: main
E/AndroidRuntime(29533): Process: me.writeily, PID: 29533
E/AndroidRuntime(29533): java.lang.RuntimeException: Unable to start activity ComponentInfo{me.writeily/me.writeily.NoteActivity}: java.lang.IllegalArgumentException: URI is not absolute: file%3A%2F%2F%2Fstorage%2Femulated%2F0%2Fgit%2Freports%2F2016-10-04.md
E/AndroidRuntime(29533):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2548)
E/AndroidRuntime(29533):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2607)
E/AndroidRuntime(29533):        at android.app.ActivityThread.access$900(ActivityThread.java:174)
E/AndroidRuntime(29533):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
E/AndroidRuntime(29533):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(29533):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(29533):        at android.app.ActivityThread.main(ActivityThread.java:5756)
E/AndroidRuntime(29533):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(29533):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(29533):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
E/AndroidRuntime(29533):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
E/AndroidRuntime(29533):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(29533): Caused by: java.lang.IllegalArgumentException: URI is not absolute: file%3A%2F%2F%2Fstorage%2Femulated%2F0%2Fgit%2Freports%2F2016-10-04.md
E/AndroidRuntime(29533):        at java.io.File.checkURI(File.java:220)
E/AndroidRuntime(29533):        at java.io.File.<init>(File.java:177)
E/AndroidRuntime(29533):        at me.writeily.model.WriteilySingleton.getFileFromUri(WriteilySingleton.java:149)
E/AndroidRuntime(29533):        at me.writeily.NoteActivity.readFileUriFromIntent(NoteActivity.java:118)
E/AndroidRuntime(29533):        at me.writeily.NoteActivity.openFromEditAction(NoteActivity.java:113)
E/AndroidRuntime(29533):        at me.writeily.NoteActivity.onCreate(NoteActivity.java:90)
E/AndroidRuntime(29533):        at android.app.Activity.performCreate(Activity.java:5619)
E/AndroidRuntime(29533):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
E/AndroidRuntime(29533):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2512)
E/AndroidRuntime(29533):        ... 11 more
W/ActivityManager(  784):   Force finishing activity me.writeily/.NoteActivity
~~~~~

**Comment by jkufner** [comment]
I believe the URLEncoder.encode is redundant at [WriteilySingleton.java, line 149](https://github.com/plafue/writeily-pro/blob/c913658da73732bd5a949d3fd0f82b6bd54bcdcd/app/src/main/java/me/writeily/model/WriteilySingleton.java#L149).
